# Generated by Django 5.2.10 on 2026-02-13 11:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc'])])),
                ('title', models.CharField(max_length=255)),
                ('upload_timestamp', models.DateTimeField(auto_now_add=True)),
                ('file_hash', models.CharField(help_text='SHA-256 hash for deduplication', max_length=64, unique=True)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata (file size, pages, etc.)')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-upload_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_text', models.TextField(help_text='Extracted text chunk')),
                ('chunk_index', models.IntegerField(help_text='Sequential position in document')),
                ('page_number', models.IntegerField(blank=True, help_text='Source page number', null=True)),
                ('embedding_vector', models.JSONField(blank=True, help_text='Vector embedding for semantic search (stored as list)', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional chunk metadata (char position, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge_base.document')),
            ],
            options={
                'ordering': ['document', 'chunk_index'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField(help_text="User's natural language query")),
                ('llm_response', models.TextField(help_text='Generated answer from LLM')),
                ('confidence_score', models.FloatField(blank=True, help_text='Confidence score (0.0-1.0)', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('feedback_rating', models.IntegerField(blank=True, help_text='User feedback rating (1-5 stars)', null=True)),
                ('response_time_ms', models.IntegerField(blank=True, help_text='Response time in milliseconds', null=True)),
                ('retrieved_chunks', models.ManyToManyField(help_text='Chunks retrieved via vector search', related_name='queries', to='knowledge_base.documentchunk')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['file_hash'], name='knowledge_b_file_ha_5c774b_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['processing_status'], name='knowledge_b_process_3b1544_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['document', 'chunk_index'], name='knowledge_b_documen_7eb428_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['page_number'], name='knowledge_b_page_nu_9da18b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentchunk',
            unique_together={('document', 'chunk_index')},
        ),
        migrations.AddIndex(
            model_name='knowledgequery',
            index=models.Index(fields=['-timestamp'], name='knowledge_b_timesta_f32c5a_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgequery',
            index=models.Index(fields=['user', '-timestamp'], name='knowledge_b_user_id_c37b55_idx'),
        ),
    ]
