# Generated by Django 5.2.10 on 2026-02-13 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('field_engineer', 'Field Engineer'), ('ops_manager', 'Operations Manager'), ('admin', 'Administrator')], default='field_engineer', max_length=20)),
                ('department', models.CharField(blank=True, help_text='Department name', max_length=100)),
                ('employee_id', models.CharField(help_text='Employee ID number', max_length=50, unique=True)),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'indexes': [models.Index(fields=['role'], name='core_userpr_role_ce56eb_idx'), models.Index(fields=['employee_id'], name='core_userpr_employe_7133ad_idx')],
            },
        ),
    ]
