# Generated by Django 5.2.10 on 2026-02-13 11:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='inspections/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('location', models.CharField(blank=True, help_text='GPS coordinates or location description', max_length=255)),
                ('equipment_type', models.CharField(choices=[('transformer', 'Transformer'), ('cable', 'Power Cable'), ('meter', 'Electricity Meter'), ('pole', 'Utility Pole'), ('switchgear', 'Switchgear'), ('substation', 'Substation Equipment'), ('other', 'Other Equipment')], max_length=50)),
                ('upload_timestamp', models.DateTimeField(auto_now_add=True)),
                ('analysis_requested', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, help_text="Inspector's notes")),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-upload_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='InspectionAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_description', models.TextField(help_text='Technical assessment from vision LLM')),
                ('risk_classification', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('safety_warnings', models.TextField(help_text='Identified safety hazards')),
                ('recommended_actions', models.TextField(help_text='Recommended next steps')),
                ('inspection_checklist', models.JSONField(default=dict, help_text='Structured checklist results (visual_damage, overheating, etc.)')),
                ('is_emergency', models.BooleanField(default=False, help_text='Critical emergency condition detected')),
                ('analysis_timestamp', models.DateTimeField(auto_now_add=True)),
                ('analyzed_by_agent', models.CharField(default='vision_llm', help_text='Which agent/model performed analysis', max_length=100)),
                ('confidence_score', models.FloatField(blank=True, help_text='Analysis confidence (0.0-1.0)', null=True)),
                ('raw_llm_output', models.JSONField(blank=True, help_text='Raw structured output from LLM', null=True)),
                ('inspection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='field_operations.fieldinspection')),
            ],
            options={
                'ordering': ['-analysis_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AgentReasoningLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(choices=[('technical_ops', 'Technical Operations Agent'), ('safety', 'Safety Compliance Agent'), ('risk', 'Risk Assessment Agent'), ('executive', 'Executive Summary Agent')], max_length=50)),
                ('agent_role', models.TextField(help_text='Agent role description')),
                ('agent_output', models.JSONField(help_text='Structured agent reasoning and conclusions')),
                ('processing_order', models.IntegerField(help_text='Sequential execution order (1, 2, 3...)')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('execution_time_ms', models.IntegerField(blank=True, help_text='Agent execution time in milliseconds', null=True)),
                ('inspection_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_logs', to='field_operations.inspectionanalysis')),
            ],
            options={
                'ordering': ['inspection_analysis', 'processing_order'],
            },
        ),
        migrations.AddIndex(
            model_name='fieldinspection',
            index=models.Index(fields=['-upload_timestamp'], name='field_opera_upload__316fbd_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldinspection',
            index=models.Index(fields=['inspector', '-upload_timestamp'], name='field_opera_inspect_8a425f_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldinspection',
            index=models.Index(fields=['equipment_type'], name='field_opera_equipme_63d7d2_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionanalysis',
            index=models.Index(fields=['risk_classification'], name='field_opera_risk_cl_8f547b_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionanalysis',
            index=models.Index(fields=['is_emergency'], name='field_opera_is_emer_8f1356_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionanalysis',
            index=models.Index(fields=['-analysis_timestamp'], name='field_opera_analysi_e10c21_idx'),
        ),
        migrations.AddIndex(
            model_name='agentreasoninglog',
            index=models.Index(fields=['inspection_analysis', 'processing_order'], name='field_opera_inspect_0b15df_idx'),
        ),
        migrations.AddIndex(
            model_name='agentreasoninglog',
            index=models.Index(fields=['agent_name'], name='field_opera_agent_n_31a7d2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='agentreasoninglog',
            unique_together={('inspection_analysis', 'processing_order')},
        ),
    ]
