# Generated by Django 5.2.10 on 2026-02-13 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('document_upload', 'Document Upload'), ('document_delete', 'Document Delete'), ('knowledge_query', 'Knowledge Query'), ('inspection_upload', 'Inspection Upload'), ('inspection_analysis', 'Inspection Analysis'), ('user_login', 'User Login'), ('user_logout', 'User Logout'), ('settings_change', 'Settings Change'), ('role_change', 'User Role Change'), ('emergency_alert', 'Emergency Alert')], max_length=50)),
                ('resource_type', models.CharField(choices=[('document', 'Document'), ('query', 'Knowledge Query'), ('inspection', 'Field Inspection'), ('user', 'User'), ('system', 'System')], max_length=50)),
                ('resource_id', models.IntegerField(blank=True, help_text='ID of the affected resource', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_role_at_time', models.CharField(help_text="User's role when action was performed", max_length=50)),
                ('request_payload', models.JSONField(blank=True, default=dict, help_text='Sanitized request data (no sensitive info)')),
                ('response_summary', models.JSONField(blank=True, default=dict, help_text='Summary of response/outcome')),
                ('success', models.BooleanField(default=True, help_text='Whether action succeeded')),
                ('error_message', models.TextField(blank=True, help_text='Error details if failed')),
                ('user_agent', models.CharField(blank=True, help_text='Browser/client user agent', max_length=255)),
                ('user', models.ForeignKey(help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='audit_audit_timesta_901180_idx'), models.Index(fields=['user', '-timestamp'], name='audit_audit_user_id_ea8c9f_idx'), models.Index(fields=['action_type', '-timestamp'], name='audit_audit_action__32de6f_idx'), models.Index(fields=['resource_type', 'resource_id'], name='audit_audit_resourc_2a3aef_idx'), models.Index(fields=['success'], name='audit_audit_success_4e92b2_idx')],
            },
        ),
    ]
